version: '4'


services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sapi
    volumes:
      - db-volume:/var/lib/postgresql/data


  api:
    image: andprof/ac2_ca
    environment:
      SPRING_PROFILES_ACTIVE: stage
      DB_HOST: database
    ports:
      - "8585:8585"
    depends_on:
      - database
volumes:
  db-volume:
